### ISSUE TITLE
❓missing ActiveReceiptRuleSet

### ISSUE THREAD

**Issue by binli0114** [vittorio-nardone/disposable_app#2]
The `ActiveReceiptRuleSet` resource is missing in the cloudformation stack. Without this resource, we can't send email to the domain.

**Comment by vittorio-nardone** [comment]
As explained in [documentation](https://www.vittorionardone.it/en/2020/01/10/your-disposable-emails-on-aws/):

"The first step in the realization of the solution is the correct configuration of the Amazon SES service. The CloudFormation template that we will use for the construction of the entire backend infrastructure **assumes that the email domain we have chosen is already correctly configured and verified**." 

ActiveReceiptRuleSet is missing because included in SES domain configuration as requirement. This allows to integrate disposable service in existing SES domains.
